spring:
  datasource:
    name: eventmanagement_datasource
    url: jdbc:mysql://localhost:3306/mydb_sdr
    username: root
    password: ftgyhu89
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /api
      default-page-size: 5

#server:
#  servlet:
#    context-path: /eventmanagement-api


logging:
  level:
    org:
      hibernate:
        type: trace